const dummyRealEstateData = [

  {
    propertyId: "RE001",
    title: "Luxury Villa with Pool",
    description: "Stunning luxury villa with a private pool, spacious garden, and modern amenities.",
    price: 1500000,
    location: {
      address: "123 Palm Tree Lane",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
    },
    propertyType: "Villa",
    area: 3500,
    numberOfBedrooms: 4,
    numberOfBathrooms: 3,
    images: [
      "https://www.ikonmarket.com/assets/images/marketing-articles/luxury-home.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSovfWMqvXYCzqSwa14K5qE4_szBykbv-xIng&s",
    ],
    listedDate: new Date("2024-08-01"),
    realtor: {
      name: "John Doe",
      contactInfo: "johndoe@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE002",
    title: "Cozy Cottage in the Countryside",
    description: "A beautiful cottage with scenic views, perfect for a weekend getaway.",
    price: 250000,
    location: {
      address: "456 Country Rd",
      city: "Nashville",
      state: "TN",
      zipCode: "37201",
    },
    propertyType: "Cottage",
    area: 1200,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    images: [
      "https://www.sobha.com/blog/wp-content/uploads/2024/08/luxury-real-estate-market-india.png",
      "https://mbluxury1.s3.amazonaws.com/2024/03/01151828/luxury-real-estate-1024x574.jpg",
    ],
    listedDate: new Date("2024-08-10"),
    realtor: {
      name: "Jane Smith",
      contactInfo: "janesmith@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE003",
    title: "Spacious Family Home",
    description: "Large family home with a backyard and modern kitchen, perfect for families.",
    price: 600000,
    location: {
      address: "789 Family St",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    propertyType: "House",
    area: 2500,
    numberOfBedrooms: 4,
    numberOfBathrooms: 2,
    images: [
      "https://mbluxury1.s3.amazonaws.com/2024/03/01151828/luxury-real-estate-1024x574.jpg",
      "https://foreignbuyerswatch.com/wp-content/uploads/2019/07/Capture-d%E2%80%99e%CC%81cran-2019-07-26-a%CC%80-13.14.52.png",
    ],
    listedDate: new Date("2024-08-15"),
    realtor: {
      name: "Mary Johnson",
      contactInfo: "maryjohnson@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE004",
    title: "Urban Apartment with City Views",
    description: "Modern apartment in the heart of the city, featuring stunning skyline views.",
    price: 950000,
    location: {
      address: "321 Urban Blvd",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
    },
    propertyType: "Apartment",
    area: 1800,
    numberOfBedrooms: 3,
    numberOfBathrooms: 2,
    images: [
      "https://www.agentadvice.com/wp-content/uploads/2020/12/shutterstock_1247473441-scaled.jpg",
      "https://static.vecteezy.com/system/resources/previews/022/902/910/non_2x/ai-generative-modern-luxury-real-estate-house-for-sale-and-rent-luxury-property-residence-concept-photo.jpg",
    ],
    listedDate: new Date("2024-08-20"),
    realtor: {
      name: "Anna Brown",
      contactInfo: "annabrown@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE005",
    title: "Luxury Loft in City Center",
    description: "Stylish loft with open floor plan, large windows, and a private terrace. Perfect for urban living.",
    price: 750000,
    location: {
      address: "10 Urban Ave",
      city: "Metropolis",
      state: "NY",
      zipCode: "10005",
    },
    propertyType: "Apartment",
    area: 1800,
    numberOfBedrooms: 2,
    numberOfBathrooms: 2,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzMOA2rmupyxv5QRAHGTvkS6KTuIPJ17EKpg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSovfWMqvXYCzqSwa14K5qE4_szBykbv-xIng&s",
    ],
    listedDate: new Date("2024-09-15"),
    realtor: {
      name: "Alice Cooper",
      contactInfo: "alicecooper@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE006",
    title: "Charming Cottage in the Woods",
    description: "A quaint 2-bedroom cottage surrounded by nature, ideal for a peaceful retreat.",
    price: 300000,
    location: {
      address: "22 Forest Lane",
      city: "Metropolis",
      state: "NY",
      zipCode: "10006",
    },
    propertyType: "House",
    area: 1200,
    numberOfBedrooms: 2,
    numberOfBathrooms: 1,
    images: [
      "https://www.sobha.com/blog/wp-content/uploads/2024/08/luxury-real-estate-market-india.png",
      "https://mbluxury1.s3.amazonaws.com/2024/03/01151828/luxury-real-estate-1024x574.jpg",
    ],
    listedDate: new Date("2024-09-20"),
    realtor: {
      name: "Brian Green",
      contactInfo: "briangreen@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE007",
    title: "Luxury Condo with Ocean View",
    description: "Exquisite condo with panoramic ocean views, modern kitchen, and top-notch amenities.",
    price: 1200000,
    location: {
      address: "30 Ocean Blvd",
      city: "Metropolis",
      state: "NY",
      zipCode: "10007",
    },
    propertyType: "Apartment",
    area: 2200,
    numberOfBedrooms: 3,
    numberOfBathrooms: 3,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzMOA2rmupyxv5QRAHGTvkS6KTuIPJ17EKpg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSovfWMqvXYCzqSwa14K5qE4_szBykbv-xIng&s",
    ],
    listedDate: new Date("2024-09-25"),
    realtor: {
      name: "Sarah Johnson",
      contactInfo: "sarahjohnson@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE008",
    title: "Spacious Family Home with Pool",
    description: "Large 5-bedroom family home with a beautiful backyard and swimming pool. Perfect for entertaining.",
    price: 650000,
    location: {
      address: "50 Sunny Rd",
      city: "Metropolis",
      state: "NY",
      zipCode: "10008",
    },
    propertyType: "House",
    area: 3000,
    numberOfBedrooms: 5,
    numberOfBathrooms: 4,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSovfWMqvXYCzqSwa14K5qE4_szBykbv-xIng&s",
      "https://mbluxury1.s3.amazonaws.com/2024/03/01151828/luxury-real-estate-1024x574.jpg",
    ],
    listedDate: new Date("2024-10-01"),
    realtor: {
      name: "Tommy Lee",
      contactInfo: "tommylee@example.com",
    },
    status: "Available",
  },
  {
    propertyId: "RE009",
    title: "Commercial Office Space",
    description: "Prime location office space available for rent. Ideal for startups and established businesses.",
    price: 4000,
    location: {
      address: "100 Business Park",
      city: "Metropolis",
      state: "NY",
      zipCode: "10009",
    },
    propertyType: "Commercial",
    area: 1500,
    numberOfBedrooms: 0,
    numberOfBathrooms: 2,
    images: [
      "https://static.vecteezy.com/system/resources/previews/022/902/910/non_2x/ai-generative-modern-luxury-real-estate-house-for-sale-and-rent-luxury-property-residence-concept-photo.jpg",
      "https://foreignbuyerswatch.com/wp-content/uploads/2019/07/Capture-d%E2%80%99e%CC%81cran-2019-07-26-a%CC%80-13.14.52.png",
    ],
    listedDate: new Date("2024-10-05"),
    realtor: {
      name: "Victoria Gray",
      contactInfo: "victoriagray@example.com",
    },
    status: "Available",
  },

];

module.exports = dummyRealEstateData;
